// <auto-generated />
using Fiap.Web.Challenge.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Web.Challenge.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240626221043_AddSensores")]
    partial class AddSensores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Web.Challenge.Models.LocalModel", b =>
                {
                    b.Property<int>("id_local")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_local"));

                    b.Property<string>("ds_coordenadas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("nm_oceano")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("id_local");

                    b.ToTable("Local", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Challenge.Models.SensoresModel", b =>
                {
                    b.Property<int>("id_sensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_sensor"));

                    b.Property<string>("ds_fabricante")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ds_modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("id_local")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nm_oceano")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("id_sensor");

                    b.HasIndex("id_local");

                    b.ToTable("Sensores", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Challenge.Models.SensoresModel", b =>
                {
                    b.HasOne("Fiap.Web.Challenge.Models.LocalModel", "Local")
                        .WithMany()
                        .HasForeignKey("id_local")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");
                });
#pragma warning restore 612, 618
        }
    }
}
